import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Currículo Fácil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <div className={styles.logo}>
          <Image src="/logo.svg" alt="Logo Currículo Fácil" width={65} height={65} />
          <div className={styles.title}>
            <h1>
              Currículo Fácil
            </h1>
            <p>
              Sem log-in, sem pagamentos, sem enrolação.
            </p>
          </div>
        </div>

        <p className={styles.about}>Sobre</p>
      </header>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
